### ISSUE TITLE
Drizzle kit is using the wrong paths seemingly

### ISSUE THREAD

**Issue by jakeleventhal** [drizzle-team/drizzle-kit-mirror#285]
I have the following docker compose
```yaml
  setup-db:
    build:
      dockerfile: ./tools/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:local@db:5432/postgres
    command: drizzle-kit push:pg
```
And the following dockerfile
```docker
FROM node:18.17.1-alpine

WORKDIR /app

RUN npm install -g drizzle-kit@latest drizzle-orm@latest
RUN npm install drizzle-orm

# Copy source files
COPY apps/client/package.json ./
COPY packages/database/drizzle.config.ts ./
COPY packages/database/src/schema.ts ./src/schema.ts
```

This works just fine, but it only seems to work if i have `drizzle-orm` installed globally and in the local scope. Otherwise, I get this error:
> Error: Cannot find module 'drizzle-orm/pg-core'
Require stack:
- /usr/local/lib/node_modules/drizzle-kit/bin.cjs
    at Module._resolveFilename (node:internal/modules/cjs/loader:1077:15)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at src/serializer/pgImports.ts (/usr/local/lib/node_modules/drizzle-kit/bin.cjs:12133:22)
    at __init (/usr/local/lib/node_modules/drizzle-kit/bin.cjs:9:56)
    at src/utils.ts (/usr/local/lib/node_modules/drizzle-kit/bin.cjs:60390:5)
    at __init (/usr/local/lib/node_modules/drizzle-kit/bin.cjs:9:56)
    at Object.<anonymous> (/usr/local/lib/node_modules/drizzle-kit/bin.cjs:62041:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/drizzle-kit/bin.cjs' ]
