### ISSUE TITLE
Issue when running drizzle-kit studio out of docker

### ISSUE THREAD

**Issue by jakeleventhal** [drizzle-team/drizzle-kit-mirror#286]
In docker, I specify the host as `--host=0.0.0.0` and it says i can access the studio at https://local.drizzle.studio?host=0.0.0.0; however, when 4983 is exposed, the only way to access the studio is by using https://local.drizzle.studio?host=localhost.

It's a bit counterintuitive.

**Comment by RobRoseKnows** [comment]
I was also struggling to figure out how to run the studio out of docker. Would be nice if there was a prebuilt docker image that I could plug into my docker-compose that would bring the studio up.

**Comment by kroucher** [comment]
+1 on the struggle. 

drizzle-kit studio running in Docker container, with ports exposed:
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/99768034/0c85ac24-8195-4d29-a090-d4a75b28ef7b)

Web fails to load, spamming console with errors:
![image](https://github.com/drizzle-team/drizzle-kit-mirror/assets/99768034/efb811bc-61cb-4cb2-ae34-107faf2c7de0)

**Comment by deadcoder0904** [comment]
is there no solution to this at all?

also, is this in development or do you guys run drizzle studio in production too with database?

would love to see your `docker-compose.yml` as i'm trying to set this up.

**Comment by jakeleventhal** [comment]
```yaml
  drizzle-studio:
    build:
      context: ../../
      dockerfile: ./path/to/Dockerfile
    ports:
      - 4983:4983
    environment:
      DATABASE_URL: postgresql://postgres:local@db:5432/postgres
      DATABASE_DIRECT_URL: postgresql://postgres:local@db:5432/postgres
    depends_on:
      setup-db:
        condition: service_completed_successfully
    restart: always
    command: drizzle-kit studio --host=0.0.0.0
```
```docker
FROM node:18.17.1-alpine

WORKDIR /app

# Install dependencies
COPY packages/artelo/database/package.json ./database-package.json
RUN npm install -g \
  "pg@$(grep -E '"pg": "(.*)"' database-package.json | cut -d: -f2 | sed 's/,//' | xargs)" \
  "drizzle-kit@$(grep -E '"drizzle-kit": "(.*)"' database-package.json | cut -d: -f2 | sed 's/,//' | xargs)" \
  "drizzle-orm@$(grep -E '"drizzle-orm": "(.*)"' database-package.json | cut -d: -f2 | sed 's/,//' | xargs)"
RUN npm install "drizzle-orm@$(grep -E '"drizzle-orm": "(.*)"' database-package.json | cut -d: -f2 | sed 's/,//' | xargs)"

# Copy source files
COPY apps/myapp/package.json ./
COPY packages/myapp/database/drizzle.config.ts ./
COPY packages/myapp/database/src/schema.ts ./src/schema.ts
```
