### ISSUE TITLE
Drizzle Studio D1 Error: `Could not read file: wrangler.toml`

### ISSUE THREAD

**Issue by ajzbc** [drizzle-team/drizzle-kit-mirror#289]
```
Error:
✘ [ERROR] Could not read file: wrangler.toml

  ENOENT: no such file or directory, open '/Users/me/Library/Application Support/drizzle-studio/wrangler.toml'
```

```ts
// ./drizzle.config.ts
import type { Config } from 'drizzle-kit';

export default {
    schema: './src/db/schema.ts',
    out: './drizzle',
    driver: 'd1',
    dbCredentials: {
        wranglerConfigPath: './wrangler.toml',
        dbName: 'NAME'
    }
} satisfies Config;
```

```toml
# ./wrangler.toml
[[d1_databases]]
binding = "DB"
database_name = "NAME"
database_id = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
migrations_dir="drizzle"
```

Seems to be using the config, but looking for the wrangler.toml file in the wrong place
